# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e086ea07ad00aed4175fed0961755a640bc550029cca15b2b97bf4825f6639f65a60ac843f7ed3c99b84701463e509228b9f82401a196ad6acfa6ba3578bb8bd

test:
  secret_key_base: f654ea2c64d4dbb8f317e25ce6d0b9b009fbaad0d2a1d8f3e2e037ac5382601b32b4be0254e3b97ad02ab159ad9158f0661fed7b2d61a894771170b0eb1f986f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
